name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          name: "ryuko"
          allow-dirty: "true"
          no-test: "true"
          secrets: | 
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'